version: '3.5'

networks:
    flask-network:
        name: flask-network

services:
    flask-test:
        container_name: flask-test-api
        image: flask-test-api
        build:
          context: .
          dockerfile: Dockerfile
        restart: unless-stopped
        networks:
          - flask-network
        ports:
          - 8000:8000
        volumes:
          - ./logs:/usr/src/app/logs
        env_file:
          - environments/.env
        privileged: true