apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deployment

spec:
  selector:
    matchLabels:
      app: flask-test-api
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-test-api
    spec:
      containers:
      - name: flask-test-api
        image: flask-test-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
