apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-test-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-test-api
  minReplicas: 2
  maxReplicas: 10